version: '3'

volumes:
  pg_data:
  static:

services:
  backend:
    image: lordsanchez/dobrotask_backend
    env_file: .env
    volumes:
      - static:/app/static_tasks_backend
    depends_on:
      - pgdb

  pgdb:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  gateway:
    image: lordsanchez/dobrotask_gateway
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/static_tasks_nginx
    depends_on:
      - backend
