version: '3'

volumes:
  pgdbdata:
  static:

services:
  backend:
    build: .
    container_name: dobrotask
    env_file: .env
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static:/app/static_tasks_backend
    # ports:
    #   - 8000:8000
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        resources:
          limits:
            cpus: '0.60'
            memory: 70M
          reservations:
            cpus: '0.30'
            memory: 30M
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    env_file: .env
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: pgdb_cont
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

  gateway:
    build: nginx/
    container_name: tasks_nginx
    ports:
      - 8000:80
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    volumes:
      - static:/static_tasks_nginx
    depends_on:
      - backend