# Generated by Django 4.2.4 on 2023-09-03 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tasksubtask_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksubtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='tasks.task', verbose_name='Задача'),
        ),
    ]
