# Generated by Django 4.2.4 on 2023-09-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_subtask',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('mid', 'Medium'), ('low', 'Low')], default='low', max_length=10, verbose_name='Приоритет'),
        ),
    ]
